linkler = {
    'dunya':['dünya'],
    'ekonomi':[
        'altın',
        'borsa',
        'döviz',
        'emlak',
        'enerji',
        'girişimcilik',
        'iş_yaşam',
        'kripto_para',
        'otomobil',
        'savunma_sanayi',
        'sigorta',
        'turizm'
                ],
    'gundem':[
        'eğitim',
        'güvenlik',
        'inanç',
        'politika'
    ],
    'magazin':[
        'dünyadan',
        'müzik',
        'televizyon'
    ],
    'saglik':[
        'cinsel_sağlık',
        'estetik_cerrahi',
        'genel_sağlık',
        'hamilelik_ve_çocuk_hastalıkları',
        'kalp_sağlığı',
        'kanser',
        'sağlıklı_beslenme'
    ],
    'spor':{
        'basketbol':[
            'basketbol',
            'dünya_şampiyonası',
            'euro_league',
            'eurocup',
            'kadınlar_euroleague',
            'milli_takım',
            'nba',
            'spor_toto_basketbol_ligi',
            'şampiyonlar_ligi'
        ],
        'futbol':[
            'almanya_ligi',
            'avrupa_ligi',
            'birinci_lig',
            'fransa_ligi',
            'ikinci_lig',
            'ingiltere_ligi',
            'ispanya_ligi',
            'italya_ligi',
            'süper_lig',
            'şampiyonlar_ligi',
            'türkiye_kupası',
            'üçüncü_lig'
        ],
        'tenis':[
            'atp',
            'grand_slam',
            'istanbul_cup',
            'kadınlar_tenis',
            'tenis'
        ],
        'voleybol':[
            'voleybol'
        ]
    },
    'teknoloji':[
        'bilişim',
        'cihaz',
        'internet',
        'mobil',
        'oyun',
        'sosyal_medya',
        'uygulama'
    ]
}